### ISSUE TITLE
Меню библиотека

### ISSUE THREAD

**Issue by 8clever** [8clever/dirtyclean#12]
Описания объектов, которые открыты пользователем

**Comment by 8clever** [comment]
Так же, задача не актуальна. Вернемся как игра будет доделана.

**Comment by mihailvityaev** [comment]
Ссылка на иконки и шаблон библиотеки - https://drive.google.com/drive/u/2/folders/1KIkQfnMCPEUQnM_8bdHhMTNczJhDLd2E

Изначально доступны иконки и описание для объектов:
1) Рука - Основной метод влияния на объекты в игре. Ей можно перемещать объекты и персонажей, либо трансформировать их в новые. Тратится при этом 1 ход
2) Одежда - Захотелось мусорить? Вперед! Дворники уже готовы к генеральной уборке. Трать её рационально: на пустую ячейку, на собаку, на другую мусорку или бомжа. Тратится при этом 1 ход
3) Время суток - Каждое утро на улицу выходит новый дворник, а каждая ночь радует себя новой собакой
4) Тюрьма - Захотел уберечь персонажа - спрячь его тут
5) Магазин - Тут можно приобрести новые объекты и персонажей
6) Дворник - Чистюля, мечтающий стать президентом. Его задача проста - очистить двор от мусора
7) Бульдозер - Появляется после сговора двух дворников. Водитель внутри любит давить свалки
8) Мусорка - Поговаривают, в городе завелся текстильный маньяк, он кидает майки и засоряет окружающую среду
9) Свалка - Бездушное ведро с бульдозерофобией, трансформируется с двух мусорок
10) Собака - Любит гонять местных кошек и чаще всего ночью
11) Домашняя собака - Одень обычную собаку в майку и посмотри, что из этого выйдет!

12) Остальные объекты (иконка и описание) под знаком вопроса и доступны только после их первого получения.

**Comment by 8clever** [comment]
@mihailvityaev 
1. нет доступа к ссылке
2. Все должно быть на анг. языке

**Comment by mihailvityaev** [comment]
Доступ предоставлен: https://drive.google.com/drive/folders/1KIkQfnMCPEUQnM_8bdHhMTNczJhDLd2E?usp=sharing
Пока делаем на русском языке

**Comment by 8clever** [comment]
ну тогда сам делай

**Comment by mihailvityaev** [comment]
@8clever Открой таску, переводы на EN:

1. Hand - The main method of influencing objects in the game. It moves objects and characters or transforms them into new figures. In this case, 1 turn is spent
2. Clothes - Do you want to litter? Forward! The janitors are already for the general cleaning. Spend it rationally: on an empty cell, on a dog, on another trash or a homeless person. In this case, 1 turn is spent
3. Time of day - Every morning a new janitor comes out on the street and every new night pleases us with a new dog
4. Prison - Wanted to save the character - hide him here
5. Shop - Here you can buy new objects and characters
6. Janitor - Excessive cleanliness lover who dreams of becoming president. He is task is simple - to clear the yard of debris
7. Bulldozer - Appears after the collusion of two janitors. The driver inside loves to crush trash cans
8. Dump - Rumor has it that a textile maniac has started up in the city, he throws T-shirts and litters the environment
9. Trash can - Soulless bucket with a bulldozer phobia, transforms from two dumps
10. Dog - Likes to chase local cats and most often at night
11. Trained Dog - Dress up a regular dog in a T-shirt and see what happens!

12. Остальные объекты (иконка и описание) под знаком вопроса и доступны только после их первого получения.
