### ISSUE TITLE
звуки убийства/раздавливания

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#133]
1) для танка, если он взаимодействует с живыми существами
2) для массона, если он взаимодействует с живыми существами

**Comment by 8clever** [comment]
@mihailvityaev звук не прикреплен к задаче

**Comment by mihailvityaev** [comment]
@8clever принимай
[kishki.zip](https://github.com/8clever/dirtyclean/files/5466066/kishki.zip)
