### ISSUE TITLE
Если пользователь имеет 0 ходов и вернулся в главное меню, свернул приложение, то ходы не начисляются

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#137]
Если пользователь имеет 0 ходов и вернулся в главное меню, свернул приложение, то ходы не начисляются.
Надо исправить баг, чтобы пользователю начисляли ходы если он в главном меню

**Comment by 8clever** [comment]
@mihailvityaev у меня не воспроизводится. Очки начисляются даже при остановленном рантайме.
