### ISSUE TITLE
Отсутствуют звуки click1_in в окнах победы и поражения

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#144]
В окне победы есть кнопка Facebook и twitter, для них не работают звуки - добавить.
И также в окне поражения - вставить, для кнопки переиграть

**Comment by 8clever** [comment]
@mihailvityaev не актуальная задача. 
1. Кнопок нет, ссылок нет.
2. Клик по меню автоматически возвращает в меню, где человек выбирает уровень.
