### ISSUE TITLE
Социализация в игре: добавить возможность Share поста для facebook и twitter из окна победы

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#145]
В окне победы есть две кнопки: facebook и twitter.
Сейчас если мы жмем в любом месте - пользователь переходит в главное меню, где ему доступен следующий уровень.

Необходимо реализовать кнопки поста/расшаривания результатов для fb+tw, чтобы кнопки были активными и при переходах пользователь мог поделиться постом в соц. сетях.

Если пользователь нажмет в любом другом месте - то он переходит в главное меню.

![photo_2020-10-30_19-45-48](https://user-images.githubusercontent.com/68809237/97733195-8faac380-1ae8-11eb-8dfa-0d3d03cf44a5.jpg)

**Comment by 8clever** [comment]
@mihailvityaev да ты я смотрю совсем с головой не дружишь.
