### ISSUE TITLE
Добавить описания и иконки в библиотеку для ходов, внутриигровой валюты и меню Миссии

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#154]
1) Добавить иконку и описание ходов (сердце):
This is your number of available moves per level. If this amount becomes equal to 0, then you will have to wait and accumulate it

2) Добавить иконку и описание $:
This is your amount of in-game currency, spend it in the shop

3) Добавить иконку и описание для звезд (меню Missions):
This is the number of completed tasks per level. To complete the level, complete them all

**Comment by 8clever** [comment]
@mihailvityaev нет отдельной иконки сердца и звезды
