### ISSUE TITLE
Изменения в библиотеке

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#160]
1) Добавтить иконку для ходов - сердца
2) Добавить иконку звезды 
3) Изменить список внутри библиотеки:

Рука
Майка
Время года
Ходы (сердце)
Доллар (внутриигровая валюта)
Звезда (меню Missions)
Тюрьма
Магаз
Дворник
Бульдозер
Мусор
Ведро
Собака
Домашняя собака

![photo_2020-11-01_15-57-27](https://user-images.githubusercontent.com/68809237/97803497-f5b75800-1c5a-11eb-960c-04495e7c88f8.jpg)

**Comment by 8clever** [comment]
@mihailvityaev Нет иконок звезды и сердца

**Comment by mihailvityaev** [comment]
@8clever 
![star](https://user-images.githubusercontent.com/68809237/97808987-2ad3a280-1c7b-11eb-966c-ccfadaf45b3c.png)
![heart](https://user-images.githubusercontent.com/68809237/97808988-2b6c3900-1c7b-11eb-8c7a-b31e78a189f0.png)
