### ISSUE TITLE
Уменьшить размер куста в магазине на 15%

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#179]
![photo_2020-11-04_14-20-14](https://user-images.githubusercontent.com/68809237/98105333-df9ed700-1ea8-11eb-9331-88bb6add32bd.jpg)

**Comment by 8clever** [comment]
@mihailvityaev там размер у всех один, это сама картинка такая

**Comment by 8clever** [comment]
@mihailvityaev кинь мне картинку другую с большими отступами от краев

**Comment by mihailvityaev** [comment]
@8clever уменьши плз ее, она выделяется своими размера очень, сек, сейчас скину

**Comment by mihailvityaev** [comment]
@8clever 
![куст](https://user-images.githubusercontent.com/68809237/98106004-ccd8d200-1ea9-11eb-8e82-6a5a5e0626ac.png)
