### ISSUE TITLE
Рекламный баннер 320х50 gif

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#182]
![320_50](https://user-images.githubusercontent.com/68809237/98713424-ab3f8500-2398-11eb-98b5-f5edac995ecf.gif)

**Comment by 8clever** [comment]
Чтобы соответствовать требованиям качества, анимированные GIF-изображения должны воспроизводиться со скоростью менее 5 кадров в секунду

**Comment by mihailvityaev** [comment]
@8clever держи:
![320_50_v2](https://user-images.githubusercontent.com/68809237/98717966-d4fbaa80-239e-11eb-8d1c-a862310fe3b1.gif)

**Comment by mihailvityaev** [comment]
@8clever 4 кадра:
![320_50_v3](https://user-images.githubusercontent.com/68809237/98719245-90710e80-23a0-11eb-84d0-45ff1a1ef946.gif)

**Comment by mihailvityaev** [comment]
![320-50-v3](https://user-images.githubusercontent.com/68809237/98721962-09bd3100-23a2-11eb-9d74-eb3733f3dd09.gif)

**Comment by mihailvityaev** [comment]
4 версия:
![320-50-4](https://user-images.githubusercontent.com/68809237/98723086-f068b480-23a2-11eb-95b9-0bd88e0b4d74.gif)

**Comment by mihailvityaev** [comment]
v5
![320-50-v5](https://user-images.githubusercontent.com/68809237/98723358-535a4b80-23a3-11eb-85d8-7c838c9df433.gif)
