### ISSUE TITLE
мент и бомж стали на одной клетке (и если бомж сверху, то при применении на него майки ничего не происходит, майка просто исчезает)

### ISSUE THREAD

**Issue by 8clever** [8clever/dirtyclean#23]

**Comment by 8clever** [comment]
У тебя вся логика завязана на то, кто кого поймает. А значит персонажи должны находится в одной клетке. Если это не так, тогда объясни каким должно быть условие.

**Comment by mihailvityaev** [comment]
Они не должны быть после хода на 1 клетке.
Можно упорядочить ходы:
1) Мент -> дошел до дворника -> на одной и мент, и уже бомж-> бомж выходит на другую ближайшую клетку 
2) или сделать так, что мент доходит до дворника, превращает его в бомжа и возвращается на свою же клетку

**Comment by mihailvityaev** [comment]
Воспроизвелось по шагам:
Дворник и мент сходили на одну и ту же ячейку:
![photo_2020-09-13_23-32-57](https://user-images.githubusercontent.com/68809237/93028006-8ab5b180-f619-11ea-8426-a67ea2115bd6.jpg)
