### ISSUE TITLE
Исчезла рука и следующий ход

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#37]
Используйте майку, затем руку при перемещении на самой ближней к ней клетке.
на эту клетку сходил дворник и убрал мусор.
получилось, что дворник убрал мусор, который схвачен рукой. из-за чего следующий ход недоступен, блокер.

![image](https://user-images.githubusercontent.com/68809237/88479326-f737fc80-cf56-11ea-8463-2064f2e6637a.png)

**Comment by 8clever** [comment]
У меня не воспроизводится
