### ISSUE TITLE
Таймер не добавляет значения ходов после окончания и всегда отображает 0

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#43]

**Comment by 8clever** [comment]
Это логично, т.к. таймер добавляет 1 жизнь. И сразу же наступает следующий ход, генерируется итем и ходят нипы и ход тут же становится 0 и вновь отрабатывает таймер

**Comment by mihailvityaev** [comment]
когда добавляется 1 ход - в значении ходов отображается 0.
и также нужно реализовать дальнейшее пополнение ходов, если у нас есть уже 1 ход - таймер работает и начисляет 2, и так до 300
