### ISSUE TITLE
Добавить в магазин покупку валуна за 500 $

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#45]

**Comment by 8clever** [comment]
Прежде чем создавать подобные задачи, то должная быть связанная задача с магазином и скринами к нему

**Comment by mihailvityaev** [comment]
Ссылка на шаблон и все текстуры магазина - https://drive.google.com/drive/folders/1uD8LtKDx7I5n6rv4XtXynsjQMZ9vh27w?usp=sharing
