### ISSUE TITLE
При нажатии на звезду появляется поп-ап с миссиями

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#48]
У каждого уровня свои 5 миссий.
Соответственно, внутри геймплея, около звезды отображаются значения при старте миссии 0/5
У 1 уровня 5 миссий:
1) Убрать 20 ячеек с мусором
2) Собрать одновременно на сетке 10 дворников
3) Сделать 10 бульдозеров
4) Сделать 5 гринписовцев
5) Сделать президента

После выполнения миссий появляется поп-ап, ура вы выиграли - пользователь возвращается в меню выбора уровней.
При этом сохраняется прогресс уровня, его можно будет потом продолжить играть.

Каждый следующий уровень доступен, если у предыдущего выполнено 3 заданий из 5.

**Comment by 8clever** [comment]
Скрины где?
