### ISSUE TITLE
Меню выбора уровней при нажатии на кнопку New Game

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#49]

**Comment by 8clever** [comment]
Скрины где?

**Comment by anmacik** [comment]
Добавь переход на другую сцену, где будет 2 кнопки, 1 - эндлесс мод,аля текущий нью гейм, но без победы при выполнении квестов, другая миссии, при нажатии которой будет переход на другую сцену, куда можно будет запихивать всякие " создать президента".
