### ISSUE TITLE
Геймплей на веб и андроид отличаются

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#50]
Необходимо реализовать все в 1 стиле и разрешении

![photo_2020-07-30_10-33-40](https://user-images.githubusercontent.com/68809237/88894184-2947a800-d250-11ea-9a2d-5b9e4c73cf4d.jpg)
![image](https://user-images.githubusercontent.com/68809237/88894333-63b14500-d250-11ea-87a9-527968d38472.png)

**Comment by 8clever** [comment]
Это старый билд, новый возьми, они не могут отличаться.

**Comment by mihailvityaev** [comment]
Они отличаются все-равно, сегодняшний билд Android и Windows, смотри по ячейкам (бекграунд и ячейки не должны отличаться):
![image](https://user-images.githubusercontent.com/68809237/88969195-259c3b80-d2b9-11ea-901c-47b4c1f4d174.png)
![photo_2020-07-30_23-05-39](https://user-images.githubusercontent.com/68809237/88969269-3cdb2900-d2b9-11ea-9ece-b8e5b71b22ed.jpg)

1) На Windows-версии ячейки отображаются на воде
2) На Андроид-версии ячейки не отображаются на воде
