### ISSUE TITLE
При использовании свалки на свалки осталась свалка и появилась крыса

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#52]
Свалка должна исчезать, воспроизвелось 2 раза

**Comment by mihailvityaev** [comment]
![image](https://user-images.githubusercontent.com/68809237/88970290-d2c38380-d2ba-11ea-840b-7e83d2c7feec.png)

**Comment by 8clever** [comment]
У меня не воспроизводится
Кинь точный репродюс степ

**Comment by mihailvityaev** [comment]
Есть предположение, что ломается логика из-за кента на ячейках.
Воспроизведу еще - скину
