### ISSUE TITLE
Масон сходил по диагонали и убил дворника

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#53]
![image](https://user-images.githubusercontent.com/68809237/88970974-e91e0f00-d2bb-11ea-96ae-bc4a7340b531.png)

**Comment by 8clever** [comment]
Вообще, такой проблемы быть не должно ты бы лучше репродюс степ кинул.

**Comment by mihailvityaev** [comment]
В предыдущей таске, которую ты закрыл, там есть видео в архиве zip.
Внутри видео все шаги записаны
