### ISSUE TITLE
При перемещении бомжа к масону - бомж становится дворником

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#54]
При перемещении бомжа к масону - бомж не должен становится дворником

**Comment by mihailvityaev** [comment]
[IMG_3764.zip](https://github.com/8clever/dirtyclean/files/5003678/IMG_3764.zip)

**Comment by 8clever** [comment]
Нет там такой логики, массон убил бомжа, произошел следущий ход и появился дворник. Т.к места для респауна ограничены и только по бокам

**Comment by mihailvityaev** [comment]
Посмотри добавленное видео, масон не должен ходить по диагоналям.
Это не первый случай, когда при перемещении к масону бомжы превращались в дворников (воспроизвелось 3 раза подряд)
