### ISSUE TITLE
Изменить дизайн кнопок в меню

### ISSUE THREAD

**Issue by anmacik** [8clever/dirtyclean#67]
Пока что добавить полупрозрачность фона и изменит цвет на зеленый.

**Comment by mihailvityaev** [comment]
1) Цвет кнопки New game должна быть зеленой
2) Добавить позади кнопок полупрозрачный фон

![photo_2020-09-24_21-25-48](https://user-images.githubusercontent.com/68809237/94184518-b011ad80-feac-11ea-9236-f5b83f67e91c.jpg)
