### ISSUE TITLE
Вставить заставку перед стартом игры

### ISSUE THREAD

**Issue by 8clever** [8clever/dirtyclean#7]

**Comment by 8clever** [comment]
Какую заставку?

**Comment by mihailvityaev** [comment]
https://www.dropbox.com/home/DirtyClean?preview=%D1%80%D0%BE%D0%BB%D0%B8%D0%BA.zip

ролик.zip называется

**Comment by 8clever** [comment]
@mihailvityaev Неправильная ссылка.

**Comment by mihailvityaev** [comment]
https://drive.google.com/drive/folders/1TSzUu7yLbG57TH014E7deFIiGVjD5txv?usp=sharing

**Comment by 8clever** [comment]
Это папка с psd файлами, явно не то.

**Comment by 8clever** [comment]
Требуется подробное описание анимации, или сделай ее сам

**Comment by mihailvityaev** [comment]
1) PNG Файлы для 1 сцены ролика (всего их 8): https://drive.google.com/drive/folders/1b1GKUWNoB4CqT62HTSr8mdk0TwW0HrUH?usp=sharing

При нажатии на кнопку New Game в главном меню экран затухает (за 1 сек) в черный цвет.
Затем за 1 сек из черного экрана появляется сама 1 сцена ролика.
Начинается он со всеми файлами, что в облаке, кроме метлы.
При нажатии на экран, слева на право, поверх ближайшего фона, появляется метла (метет за 1 секунду).
Позади метлы, ближайший фон исчезает, когда метла посередине (т.е. на 0.5 секунде).

Дальнейшее нажатие приведет игрока к аналогичному поведению, только со средним фоном
Дальнейшее нажатие приведет игрока к аналогичному поведению, только с задним фоном

При дальнейшем нажатии на экран затухает в 1 секунду черный цвет (дальше начинается 2 сцена)

**Comment by mihailvityaev** [comment]
2. PNG Файлы для 2 сцены ролика:
https://drive.google.com/drive/folders/1D4CDmQFvp3XoUb8Viyw_-pcVVT7sbMpL?usp=sharing

Из черного цвета появляется бекграунд с птицами1
При нажатии птицы меняются на птицы2
При нажатии экран затухает в черный цвет (дальше начинается 3 сцена)

**Comment by mihailvityaev** [comment]
3 Файлы для 3 сцены ролика:
https://drive.google.com/drive/folders/1P_SHwBbvvU3WtugZKqERWkROLGQVhstb?usp=sharing

Из черного цвета появляются одновременно: синий фон, поверх него не уставший дворник и метла с руками.
При нажатии на экран дворник смахнул метлой
Потом при нажатии на экран он еще раз смахнул метлой
При нажатии на экран стемнело (поверх всех слоев появился красный с полупрозрачностью)
При нажатии на экран дворник заменяется на уставшего
При нажатии на экран экран стухает в черный цвет (дальше начинается 4 сцена)

**Comment by mihailvityaev** [comment]
4) Файлы для 4 сцены ролика: 
https://drive.google.com/drive/folders/1a473LyLzoy59s4wMsXPKvx6ek9CsucZw?usp=sharing

Из черного цвета появляются одновременно: Самый задний фон, дворник с открытыми глазами и Руки - самый верхний слой
При нажатии на экран дворник смехнул метлой вниз и вверх (вернул состоянии руки в исходное состояние)
При нажатии на экран появляется бухающий школьник
При нажатии на экран бухающий школьник сменяется на дочку с мамой
При нажатии на экран дочка с мамой сменяются на курильщика
При нажатии на экран курильщик сменяется на мусор
При нажатии на экран дворник меняется на того, кто с закрытыми глазами
При нажатии на экран позади дворника появились крыса и кошка
При нажатии на экран он затухает в черный цвет (дальше начинается 5 сцена)

**Comment by mihailvityaev** [comment]
5. Файлы для 4 сцены ролика:
https://drive.google.com/drive/folders/1RSgh__xFQdk-KyoBS6yNTiEhsvblzpu-?usp=sharing

Из черного цвета появляется: задний фон
При нажатии на экран происходит наложение слоев - поверх всего добавляется свечение1
При нажатии на экран происходит наложение слоев - поверх всего добавляется свечение2
При нажатии на экран происходит наложение слоев - поверх всего добавляется свечение3
При нажатии на экран он затухает в черный цвет (дальше начинается 6 сцена)

**Comment by mihailvityaev** [comment]
6) https://drive.google.com/drive/folders/1b3wUnVqnISR6TOXVxx9_xX0f08TXSWqZ?usp=sharing

Из черного цвета появляются одновременно: задний фон1 и поверх него слой с метлой
При нажатии на экран дворник сделал движение смахивания мусора и руки вернулись в своей состояние (действие в 1 секунду)
При нажатии на экран происходит замена слоев Задний фон1 на задний фон2, метла поменялась на руки1
При нажатии на экран происходит замена слоев руки1 на руки2
При нажатии на экран он затухает в черный цвет (дальше начинается 7 сцена)

**Comment by mihailvityaev** [comment]
7. https://drive.google.com/drive/folders/1DYB4YVyB62VX_4-2nFvSkwVbzD9nAB7X?usp=sharing

Из черного цвета появляется файл вот
При нажатии на экран он затухает в черный цвет (дальше начинается 8 сцена)

**Comment by mihailvityaev** [comment]
8. https://drive.google.com/drive/folders/1KC2b_sTk9AJ59yLTniEKZpeRjwITRqX1?usp=sharing

Из черного цвета появляется файл - задний фон
При нажатии на экран накладывается слой листья
При нажатии на экран накладывается слой газета
При нажатии на экран он затухает в черный цвет и происходит переход в геймплей

**Comment by mihailvityaev** [comment]
Ссылка на облако и ролик, где доступны все 8 сцен - https://drive.google.com/drive/folders/1WdhUu5-icDzY9mM7xEt63CNIX_xhystl?usp=sharing
