### ISSUE TITLE
Сделать окно Задания, подобное, как у SHOP

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#70]
1) Оно открывается по нажатию на звезды 0/5
2) Подобное окно должно быть меньше по вертикали, чем у SHOP
3) Изменить цвет текста на черный
4) Если задание выполнено, то оно зачеркнуто посередине текста полосой ( ̶З̶а̶ч̶е̶р̶к̶н̶у̶т̶ы̶й̶)
5) Добавить клетку - если задание не выполнено, добавить галочку, если задание выполнено
![galochka2](https://user-images.githubusercontent.com/68809237/94186994-0af8d400-feb0-11ea-91a0-f1060bd4cdeb.png)
![galochka1](https://user-images.githubusercontent.com/68809237/94186998-0c2a0100-feb0-11ea-8722-65c945bee8b7.png)

**Comment by 8clever** [comment]
А я типа такой сам давай фотошопить окно? Картинку сюда залей @mihailvityaev

**Comment by mihailvityaev** [comment]
![Uploading Mission.jpg…]()

**Comment by mihailvityaev** [comment]
![Mission](https://user-images.githubusercontent.com/68809237/94345823-5be40600-0031-11eb-83bc-6f464c3fa50f.jpg)

**Comment by mihailvityaev** [comment]
Также изменил цвет галочки и размер png-картинок
![галочка](https://user-images.githubusercontent.com/68809237/94345908-d876e480-0031-11eb-94ad-0403cc12f813.png)
![ячейка](https://user-images.githubusercontent.com/68809237/94345910-d9a81180-0031-11eb-84dc-aae9764ed1d3.png)

**Comment by 8clever** [comment]
Не ну ты норм?
Текст зачем мне?
Пикчу магаза просто, без текста
@mihailvityaev

**Comment by mihailvityaev** [comment]
Текст заголовков поп-апов: Calibri + верхний регистр + белый текст + 2px черной обводки.
В PSD проекте их размер 18,14 пт

![окно с крестиком](https://user-images.githubusercontent.com/68809237/94357665-6b039c00-00a3-11eb-97ee-5b78651492f5.png)
![окно без крестика](https://user-images.githubusercontent.com/68809237/94357668-6c34c900-00a3-11eb-8628-f72fab12a194.png)
