### ISSUE TITLE
Добавить 2 уровень

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#71]
![16X9 - 2560X1440 2 уровень](https://user-images.githubusercontent.com/68809237/94196817-9462d300-febd-11ea-89e2-bb25f4e9d0ac.jpg)
![16X10 - 2560X1600 2 уровень](https://user-images.githubusercontent.com/68809237/94196889-ac3a5700-febd-11ea-9351-ed9a162b8e03.jpg)
![Главное меню 4х3 1920х2560 2 уровень](https://user-images.githubusercontent.com/68809237/94196913-b0667480-febd-11ea-9535-a36c1969c54f.jpg)

**Comment by 8clever** [comment]
Клетки где должны быть? @mihailvityaev

**Comment by mihailvityaev** [comment]
Ебани 15 сверху и 15 снизу, примерно так:
![photo_2020-09-26_19-22-37](https://user-images.githubusercontent.com/68809237/94345321-b9765380-002d-11eb-8321-5f2990b3225d.jpg)
