### ISSUE TITLE
Если приобрести дважды подряд крыс при 0 количестве ходов, то количество ходов переходит в минусовое значение

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#77]
![photo_2020-09-27_21-36-33](https://user-images.githubusercontent.com/68809237/94372812-991bc700-0109-11eb-9124-37b884b7e561.jpg)

**Comment by 8clever** [comment]
Хватит тупить. Логично, что при 0, у тебя не будет итема, а покупка генерирует итем и тем самым позволяет сделать ход. Мы либо запрещаем отображать шоп при 0, либо оставляем так. Прям капитан очевидность.
@mihailvityaev

**Comment by mihailvityaev** [comment]
@8clever логично - это когда минимальное значение = 0 и не уменьшается ниже.
При покупке 1 итема сделай добавление +1 хода игроку плз.

**Comment by 8clever** [comment]
Ну вот так бы сразу 
@mihailvityaev
