### ISSUE TITLE
Крокодил во 2 уровне слишком растянут по вертикали

### ISSUE THREAD

**Issue by mihailvityaev** [8clever/dirtyclean#79]
Прикрепил настройки устройства, с которого вытянут бекграунд:

![photo_2020-09-27_21-52-31](https://user-images.githubusercontent.com/68809237/94373110-c8333800-010b-11eb-8844-554c63bcceba.jpg)
![photo_2020-09-27_21-52-40](https://user-images.githubusercontent.com/68809237/94373113-cb2e2880-010b-11eb-8803-abc36c1846b8.jpg)

**Comment by 8clever** [comment]
да плевать на устройство
